services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - db

    queue:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_queue
        working_dir: /var/www
        command: php -d memory_limit=512M artisan queue:work
        volumes:
            - .:/var/www
        depends_on:
            - app
            - db
        restart: always

    db:
        image: mysql:8
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - data:/var/lib/mysql

volumes:
    data:
